### ISSUE TITLE
Could you please provide generate_star function?

### ISSUE THREAD

**Issue by helloxueen** [qyp2000/TLDNN#1]
Your code is awesome, and is of much useful, in addition, could you please provide generate_star function? the function is not in the code.

**Comment by Miraitwo** [comment]
Hello,
﻿
I am very interested in your research project and have been reading through your code. I noticed that in dataloader2.py, the generate_star function is called, but I couldn't find the definition of this function anywhere in the repository. If possible, could you provide me with the implementation of this function?
﻿
Thank you very much, and I look forward to your response.
﻿
Best regards

**Comment by qyp2000** [comment]
The purpose of this section is to reserve an interface for generating constellation diagrams, but it was not called in the algorithm, so we did not write this module.
